# 端口
server:
  port: 8091


 #配置 rocketmq
rocketmq:
  name-server: 118.178.243.174:9876
  #生产者
  producer:
    #生产者组名，规定在一个应用里面必须唯一
    group: plan-dev-producer
    #消息发送的超时时间 默认3000ms
    send-message-timeout: 3000
    #消息达到4096字节的时候，消息就会被压缩。默认 4096
    compress-message-body-threshold: 4096
    #最大的消息限制，默认为128K
    max-message-size: 4194304
    #同步消息发送失败重试次数
    retry-times-when-send-failed: 3
    #在内部发送失败时是否重试其他代理，这个参数在有多个broker时才生效
    retry-next-server: true
    #异步消息发送失败重试的次数
    retry-times-when-send-async-failed: 3

spring:
  datasource:
    url: jdbc:mysql://rm-cn-9lb381kv40002sao.rwlb.rds.aliyuncs.com:3306/plan_gateway?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: yhx123456@
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    # Redis服务器地址
    host: r-bp10xew38rvrgoqv7ypd.redis.rds.aliyuncs.com
    # Redis服务器端口号
    port: 6379
    # 使用的数据库索引，默认是0
    database: 0
    # 连接超时时间
    timeout: 1800000
    lettuce:
      pool:
        # 最大阻塞等待时间，负数表示没有限制
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 5
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中最大连接数，负数表示没有限制
        max-active: 20
  application:
    name: users-center
  cloud:
    nacos:
      server-addr: http://118.178.243.174:8848
      #服务发现
      discovery:
        server-addr: http://118.178.243.174:8848
        namespace: 17c292c6-c34b-4d40-9ef2-33fc673b8342
        group: dev


mybatis-plus:
  global-config:
    db-config:
      #id类型: 雪花算法实现
      id-type: assign_id
  configuration-properties:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射 address_book ---> addressBook
    map-underscore-to-camel-case: false
    #mybatis-plus配置控制台打印完整带参数SQL语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: pojo

logging:
    #  开发阶段不持久化日志，debug模式可以看sql
    #  file:
    #    path: E:\\FinishDesigning\\log
    #    name: job.log
  level:
    com.job: debug