server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://rm-cn-9lb381kv40002sao.rwlb.rds.aliyuncs.com:3306/plan_gateway?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: yhx123456@
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
      # Redis服务器地址
    host: r-bp10xew38rvrgoqv7ypd.redis.rds.aliyuncs.com
      # Redis服务器端口号
    port: 6379
      # 使用的数据库索引，默认是0
    database: 0
      # 连接超时时间
    timeout: 1800000
    lettuce:
      pool:
          # 最大阻塞等待时间，负数表示没有限制
        max-wait: -1
          # 连接池中的最大空闲连接
        max-idle: 5
          # 连接池中的最小空闲连接
        min-idle: 0
          # 连接池中最大连接数，负数表示没有限制
        max-active: 20
    password: Yanghaixiong0315@
  application:
    name: plan-gateway
  cloud:
    #注册中心配置
    nacos:
      server-addr: http://118.178.243.174:8848
      #服务发现
      discovery:
        server-addr: http://118.178.243.174:8848
        namespace: 17c292c6-c34b-4d40-9ef2-33fc673b8342
        group: dev
    #网关配置
    gateway:
      routes:
        - id: user-center-8091
          uri: http://localhost:8091
          predicates:
            - Path=/user/**


