# 端口
server:
  port: 8092

#配置 rocketmq
rocketmq:
  name-server: 118.178.243.174:9876

spring:
  redis:
    # Redis服务器地址
    host: localhost
    # Redis服务器端口号
    port: 6379
    # 使用的数据库索引，默认是0
    database: 0
    # 连接超时时间
    timeout: 1800000
    lettuce:
      pool:
        # 最大阻塞等待时间，负数表示没有限制
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 5
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中最大连接数，负数表示没有限制
        max-active: 20
  application:
    #服务吗
    name: third-party-service
  cloud:
    nacos:
      server-addr: http://118.178.243.174:8848
      #服务发现
      discovery:
        server-addr: http://118.178.243.174:8848
        namespace: 17c292c6-c34b-4d40-9ef2-33fc673b8342
        group: dev

logging:
  #  开发阶段不持久化日志，debug模式可以看sql
  #  file:
  #    path: E:\\FinishDesigning\\log
  #    name: job.log
  level:
    com.job: debug

